config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :products do
    collection do
      get :import_form
      post :import
    end
     post :add_to_cart, on: :member
  end

  resources :cart, only: :index do
    collection do
      delete '/delete_item/:product_id', to: 'cart#delete_item', as: 'delete_item'
      post :order
    end
  end

  resources :users, only: :index

  namespace :api do
    namespace :v1, defaults: {format: :json} do
      resources :products, only: %i(index show create) do
        patch :update_price, on: :member
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :order, Cart
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  def initialize(session)
    @session = session
    @cart = @session[:cart] || {}
  end

  # Add item to cart
  def add_item(product_id)
    @cart[product_id].blank? ? @cart[product_id] = 1 : @cart[product_id] += 1
    @session[:cart] = @cart
  end

  # Delete item from cart
  def delete_item(product_id)
    if @cart[product_id].present?
      @cart[product_id] > 1 ? @cart[product_id] -= 1 : @cart.delete(product_id)
    end
    @session[:cart] = @cart
  end

  # Empty cart
  def empty
    @session[:cart] = nil
  end

  # Display items in cart
  def items_for_cart
    @cart.map do |key, value|
      product = Product.find_by(id:key)
      if product.present?
        {
          id: product.id,
          name: product.name,
          brand: product.brand,
          model: product.model,
          sku: product.sku,
          price: product.price,
          quantity: value,
          total_item_price: product.price * value
        }
      else
        nil
      end
    end
  end

  # Items for order
  def items_for_order
    @cart.map do |key, value|
      {
        product_id: key,
        quantity: value
      }
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  accepts_nested_attributes_for :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :brand, :sku, :model, :price, presence: true
  validates :price, numericality: true

  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.notify_about_account_creation(self).deliver
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::Base
  around_action :verify_token

  private

  def verify_token
    if request.headers['TOKEN'] == ENV['API_SECURE_TOKEN']
      yield
    else
      render json: { error: 'Please provide valid token'}, status: 401
    end
  end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::ApiController
  load_and_authorize_resource

  def index
    render json: @products, status: :ok
  end

  def show
    render json: @product, status: :ok
  end

  def create
    if @product.save
      render json: @product, status: :created
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

  def update_price
    if @product.update_attribute(:price, params[:price])
      render json: @product, status: :created
    else
      render json: @product.errors, status: :unprocessable_entity
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :brand, :model, :sku, :price, :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :set_cart, only: %i(add_item delete_item index order)

  def index
    @items = @cart.items_for_cart
  end

  def add_item
    @cart.add_item_to_cart(params[:product_id])
    @items = @cart.items_for_cart
  end

  def delete_item
    @cart.delete_item(params[:product_id])
    @items = @cart.items_for_cart
    redirect_back(fallback_location: cart_index_path)
  end

  def order
    @items = @cart.items_for_order
    order = Order.new(user: current_user, order_items_attributes: @items)

    if order.save!
      flash[:success] = 'Order has been created successfully'
      @cart.empty
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to root_path
    end
  end

  private

  def set_cart
    @cart = Cart.new(session)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource except: :add_to_cart

  def index
  end

  def create
    if @product.save
       flash[:notice] = 'Product has been added'
    else
      flash[:error]  = @product.errors.full_messages.to_sentence
    end
    redirect_to products_path
  end

  def import
    if ProductsImporter.from_json(file: params.dig(:products, :file).path)
      flash[:notice] = 'Products have been successfully imported'
    else
      flash[:error] = 'Wrong file format'
    end
    redirect_back(fallback_location: root_path)
  end

  def add_to_cart
    product_id = params[:id]
    cart = Cart.new(session)
    cart.add_item(product_id)
    redirect_back(fallback_location: root_path)
  end

  private

  def product_params
    params.require(:product).permit(:name, :desc, :price, :sku, :model, :brand)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES_MAP = {
    notice: :success,
    alert: :danger,
    error: :danger,
    info: :info,
    warning: :warning
  }.freeze

  def bootstrap_flash
    safe_join(flash.each_with_object([]) do |(type, message), messages|
                next if message.blank? || !message.respond_to?(:to_str)
                type = ALERT_TYPES_MAP.fetch(type.to_sym, type)
                messages << flash_container(type, message)
              end, "\n").presence
  end

  def flash_container(type, message)
    content_tag :div, class: "alert alert-#{type} alert-dismissable" do
      button_tag type: "button", class: "close", data: { dismiss: "alert" } do
        "&times;".html_safe
      end.safe_concat(message)
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/v1/products_helper.rb
module V1::ProductsHelper
end

app/views/cart/index.html.haml
%br
%br
%h3 Cart
%table.table-hover.table-bordered
  %thead
    %th
      Name
    %th
      Price
    %th
      Actions
  %tbody
    - @items.each do |item|
      %tr
      %td
        = item[:name]
      %td
        = number_to_currency(item[:price])
      %td
        = button_to 'Delete', delete_item_cart_index_path(product_id: item[:id]), method: :delete, class: 'btn btn-sm btn-danger'
  %tfoot
    %tr
      %td
        = button_to 'Buy', order_cart_index_path, class: 'btn btn-info'

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-default.navbar-fixed-top.navbar-inverse{ role: 'navigation' }
    .container
      .navbar-brand
        = link_to 'SimpleShop', root_path
      %p.navbar-text
        = "Welcome, #{current_user.email}" if current_user
      .nav
        %ul.nav.nav-pills.navbar-right
          %li= link_to 'Cart', cart_index_path, class: 'nav-item'
          - unless current_user
            %li= link_to 'Register', new_user_registration_path
            %li= link_to 'Sign in', new_user_session_path
          - if current_user && current_user.admin?
            %li= link_to 'Users', users_path
          %li= link_to 'Exit', destroy_user_session_path, method: :delete if current_user

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Simpleshop
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container
      = bootstrap_flash

      = yield

app/views/products/_form.html.haml
.row
  .col-md-6
    = form_for :products, url: import_products_path, html: { multipart: true, class: 'form-inline' } do |f|
      .form-group
      = f.label 'Import products'
      = f.file_field :file, class: 'form-control', accept: '.json'
      = f.submit 'Import', class: 'btn btn-primary'
.row
  .col-md-4
    = form_for :product, url: products_path, html: {class: 'form-horizontal'} do |f|
      .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
      .form-group
      = f.label :brand
      = f.text_field :brand, class: 'form-control'
      .form-group
      = f.label :model
      = f.text_field :model, class: 'form-control'
      .form-group
      = f.label :sku
      = f.text_field :sku, class: 'form-control'
      .form-group
      = f.label :price
      = f.number_field :price, class: 'form-control'
      .form-group
      = f.label :desc
      = f.text_area :desc, class: 'form-control'
      .form-group
      = f.submit 'Add product', class: 'btn btn-primary'

app/views/products/_product.html.haml
.col-md-4
  %h4
    = product.name
  %p
  = product.brand
  %p
  = product.model
  %p
  = number_to_currency(product.price)
  %p
    %button.btn.btn-info(data-target="#product_#{product.id}" data-toggle="modal" type="button") Detaied view
  = render 'product_modal', product: product

app/views/products/_product_modal.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "productModalLabel", :role => "dialog", :tabindex => "-1", "id" => "product_#{product.id}"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header
        %h5.modal-title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %h4
          = product.name
        %p
        = product.brand
        %p
        = product.model
        %p
        = number_to_currency(product.price)
        %p
        = product.desc
        %br
        = button_to 'Add to Cart', add_to_cart_product_path(product.id), class: 'btn btn-info'
      .modal-footer
        %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} Close

app/views/products/index.html.haml
%h3 Products List
.row
  .col-md-12
    - if user_signed_in? && current_user.admin?
      = render 'form'
    .row
      - @products.each do |product|
        = render 'product', product: product

app/views/users/index.html.haml
%h3 Users List
.row
  .col-md-12
    %ul.list-group
      - @users.each do |user|
        %li.list-group-item= user.email